import {installPreciseLateAim,aimLateSurface} from './LabLateCampaignAim.js';
import * as THREE from 'three';
const V=(...p)=>new THREE.Vector3(...p),check=(ok,msg)=>{if(!ok)throw Error(msg);};
function floorEnter(d,p){const before=d.game.teleportCount,f=p.getFrame();d.walk(f.center.x,f.center.z-3);if(d.game.teleportCount===before)d.walk(f.center.x,f.center.z);d.until(()=>d.game.teleportCount>before,5,'Ordinary gravity traversal missed prepared floor aperture');d.wait(.65);}
function hopWalk(d,x,z){let reached=false;for(let n=0;n<240;n++){const dx=x-d.game.playerPosition.x,dz=z-d.game.playerPosition.z,r=Math.hypot(dx,dz);if(r<.3){reached=true;if(d.game.playerGrounded){d.stop();return;}}if(!reached&&n%45===0)d.game.input.jumpQueued=true;const pace=Math.min(1,r*1.5);if(r>.01)d.worldMove(dx/r*pace,dz/r*pace);else d.stop();d.frame();}d.stop();throw Error('Actual low cup rim blocked the ordinary inspection jump');}
function collectCup(d,name){const p=d.game.cargo.position.clone();if(name==='b'){d.walk(p.x,-6);d.walk(p.x,-4.85);if(d.game.interact()){check(d.game.heldCube,'Cup inspection interaction missed the original cargo');d.wait(.55);return;}const x=p.x+.35;hopWalk(d,x,Math.max(p.z-1.1,-3.5));d.pickup();hopWalk(d,x,-5.7);return;}d.walk(-12,-15);d.walk(-12,-3);d.walk(p.x,-3);d.walk(p.x,-1.95);d.pickup();d.walk(p.x,-4);d.walk(-12,-4);d.walk(-12,-5);}
function deliver(d,p){const {game:g}=d,f=p.getFrame();d.look(f.center);d.walk(f.center.x,f.center.z+2.5);d.walk(f.center.x,f.center.z+.72);d.wait(.6);check(g.interact()&&!g.heldCube,'Original free cargo could not enter prepared floor');d.walk(f.center.x,f.center.z+2.8);}
export function recoverPuzzleProgression50(d){d.walk(-29,11);d.until(()=>d.game.playerGrounded&&d.game.playerPosition.y< -3.8,6,'Missed court must reach dry physical service floor');d.walk(-29,-18);d.walk(-39.2,-18);d.walk(-39.2,20);d.walk(-29,27);d.mark('Continuous dry service floor and broad real ramp recover the missed court');}
/** Inputs only: walk, look, shoot, E, ordinary jump and gravity. In particular the
 * installed exit is never reassigned when its common physical hinge returns. */
export function runPuzzleProgression50(d,{stopAfter=null,recover=false,noCargo=false,leaveCargo=false,swapColours=false}={}){
 installPreciseLateAim(d);const {game:g,level:l}=d,r=l.rotor;check(l.puzzleProgression50,'Wrong folded rift room');if(recover)recoverPuzzleProgression50(d);
 const aim=(color,surface,point)=>aimLateSurface(d,swapColours?1-color:color,surface,point);
 d.walk(-22,25);aim(0,l.cargoFeed.surface);d.walk(-34,25);aim(1,r.cups[0].feed);d.walk(-30,29);if(!noCargo)d.pickup();
 if(noCargo){d.wait(4);check(Math.abs(r.angle)<.03&&!r.loaded('a')&&!r.loaded('b'),'Empty hinge must remain at its real spring equilibrium');return;}
 deliver(d,l.cargoFeed.surface);d.until(()=>r.loaded('a')&&r.angle>1.48,25,'Original cargo contact did not turn the real first hinge');d.wait(4);d.mark('Original free weight rotates the true common hinge against the first physical stop');if(stopAfter==='loaded-a')return;
 d.walk(-30,25);aim(0,l.departureEntry);aim(1,r.paneA);d.enter(l.departureEntry);d.until(()=>g.playerGrounded&&g.playerPosition.y>6.08&&g.playerPosition.y<6.5,5,'First rotating pane missed its fixed west gallery');d.walk(-12,-9);d.mark('Rotated first pane reaches a permanent west gallery');if(stopAfter==='gallery-a')return;
 d.walk(-12,-7);aim(0,l.galleryFeed.surface);d.walk(-6.5,-15.5);aim(1,r.cups[1].feed);d.mark('First weighted pose exposes the opposite freight head and its portal is prepared before return');if(stopAfter==='prepared-b')return;
 collectCup(d,'a');d.until(()=>Math.abs(r.angle)<.06&&Math.abs(r.body.angularVelocity.z)<.008&&r.cups.every(c=>Math.abs(c.body.angularVelocity.z)<.015),35,'Removing the actual first weight did not return and settle the common spring hinge');d.mark('Retrieve the original weight; its empty hinge returns while the prepared opposite freight address travels');if(stopAfter==='returned')return;
 deliver(d,l.galleryFeed.surface);d.until(()=>r.loaded('b')&&r.angle< -1.48,25,'Same original weight did not reach and turn the opposite cup');d.wait(4);d.mark('The same cargo crosses the prepared pair and rotates the common hinge in the opposite direction');if(stopAfter==='loaded-b')return;
 // The second white face looks east. The dry service floor gives its actual
 // opposite shooting view, rather than a back-face aim through a closed wall.
 d.walk(-12,-19.5);d.until(()=>g.playerGrounded&&g.playerPosition.y< -3.8,6,'West gallery service descent missed');d.walk(-20,-28);d.walk(24,-28);d.walk(30,-30);const secondFace=r.paneB.getFrame();aim(1,r.paneB,secondFace.center.addScaledVector(secondFace.right,-3.1));d.walk(24,-28);d.walk(-39.2,-28);d.walk(-39.2,20);d.walk(-30,25);aim(0,l.departureEntry);d.enter(l.departureEntry);d.until(()=>g.playerGrounded&&g.playerPosition.y>6.08&&g.playerPosition.y<6.5,5,'Opposite rotating pane missed the fixed east gallery');d.mark('Opposite service view addresses the second moving pane and reaches its fixed east gallery');if(stopAfter==='gallery-b')return;
 d.walk(12,-7);aim(0,l.finalFeed.surface);const exit=g.portals.portals[swapColours?0:1],oldNormal=exit.normal.clone();d.mark('Prepare the final gallery floor while the existing wall exit remains on its real hinged pane');if(stopAfter==='prepared-final')return;
 collectCup(d,'b');
 d.until(()=>Math.abs(r.angle)<.06&&Math.abs(r.body.angularVelocity.z)<.008&&r.cups.every(c=>Math.abs(c.body.angularVelocity.z)<.015),35,'Removing opposite cargo did not return and settle the actual common hinge');check(g.portals.portals[swapColours?0:1]===exit&&exit.normal.distanceTo(oldNormal)>.9,'The same installed exit must rotate with its physical pane');d.mark('Removing the second live weight turns the already installed wall aperture into the upper floor');if(stopAfter==='rotated-final')return;
 if(leaveCargo){d.walk(14,5);d.look(V(16,7,5));d.wait(.6);check(g.interact()&&!g.heldCube,'Original cargo could not be left on the real east gallery');d.wait(1);}
 floorEnter(d,l.finalFeed.surface);d.until(()=>g.playerGrounded&&g.playerPosition.y>21.9,6,'The returned floor aperture did not deliver both original actors to its upper court');d.look(V(11,24,-20));d.walk(11,-18);if(leaveCargo){d.wait(2);check(g.state!=='won'&&g.playerPosition.y>21.9&&g.playerPosition.distanceTo(g.cargo.position)>4,'Passenger alone must reach but not complete the upper joint goal');d.mark('Original passenger reaches the upper court while the original cargo remains on the lower gallery');return;}d.until(()=>g.state==='won',4,'Original actors did not share the upper joint goal');d.mark('Both original travellers finish through the same physically returned aperture');
}
