import * as THREE from 'three';
import {V} from './LabSingularityKit.js';
const check=(p,m)=>{if(!p)throw Error(m);},UP=V(0,1,0),angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
/** Read-only route planning plus ordinary movement, E, jump and aimed shots.
 * The driver never sets an actor position, velocity, portal or puzzle signal. */
export async function runSingularityJourney(game,{onMilestone=()=>{},stopAfter=null,order=null,onFrame=null,annexVariant='direct'}={}){
 const level=game.firstLevel;check(level.singularity&&game.state==='playing','Start the new Tower through Play');
 check(level.completedStages===0,'A route must start with an untouched attempt');
 const original={move:game.input.getMove,reset:game.resetRun,respawn:game.respawn,cargoReset:game.physics.resetCargo};
 const companion=game.cargo,body=game.physics.cargoBody.id,move=new THREE.Vector2();
 const report={id:level.id,level:41,pass:false,frames:0,physicsSteps:0,seconds:0,activeSeconds:0,distance:0,shots:0,jumps:0,interactions:0,resets:0,respawns:0,cargoResets:0,milestones:[],actions:[],maxIdleSeconds:0};
 let idle=0,previousYaw=game.yaw,previousPitch=game.pitch;
 game.input.getMove=()=>move.clone();
 game.resetRun=function(...a){report.resets++;return original.reset.apply(this,a);};game.respawn=function(...a){report.respawns++;return original.respawn.apply(this,a);};game.physics.resetCargo=function(...a){report.cargoResets++;return original.cargoReset.apply(this,a);};
 const S=()=>({frame:report.frames,seconds:report.physicsSteps/120,player:game.playerPosition.toArray(),cargo:game.cargo.position.toArray(),solved:level.getTowerMetrics().solvedIds,state:game.state});
 function stop(){move.set(0,0);game.input.keys.clear();}
 function worldMove(x,z){const p=V(x,0,z).applyAxisAngle(UP,-game.yaw);move.set(p.x,p.z);}
 function turn(dx,dz){const desired=Math.atan2(-dx,-dz);game.yaw+=THREE.MathUtils.clamp(angle(desired-game.yaw),-.065,.065);game.pitch+=THREE.MathUtils.clamp(-.14-game.pitch,-.025,.025);}
 async function frame(){
  const before=game.playerPosition.clone();for(let s=0;s<2&&game.state==='playing';s++){game.updatePlaying(1/120);report.physicsSteps++;}
  game.updateVisuals(1/60,1);const distance=before.distanceTo(game.playerPosition);report.distance+=distance;
  const active=distance>.0001||Math.abs(angle(game.yaw-previousYaw))+Math.abs(game.pitch-previousPitch)>.0001;report.activeSeconds+=active?1/60:0;idle=active?0:idle+1/60;report.maxIdleSeconds=Math.max(idle,report.maxIdleSeconds);previousYaw=game.yaw;previousPitch=game.pitch;
  check(game.cargo===companion&&game.physics.cargoBody.id===body,'Companion identity changed');check(!report.resets&&!report.respawns&&!report.cargoResets,'A Tower attempt reset');
  if(onFrame)await onFrame({...S(),visualFrame:report.frames,cargoBodyId:body});
  if(globalThis.__SINGULARITY_FRAME__)await globalThis.__SINGULARITY_FRAME__({...S(),visualFrame:report.frames,cargoBodyId:body});
  report.frames++;if(report.frames%120===0){
   await globalThis.__SINGULARITY_FLUSH__?.();
   // A long microtask-only route starves Chromium's canvas/GPU message pump.
   // Let the browser retire canvas updates even when recording is disabled.
   // This yields wall time only: every physics and animation frame is retained.
   if(typeof window!=='undefined'&&typeof window.requestAnimationFrame==='function')await new Promise(resolve=>setTimeout(resolve,0));
  }
 }
 async function wait(s){stop();for(let i=0;i<Math.ceil(s*60);i++)await frame();}
 async function until(predicate,seconds,label){stop();for(let i=0;i<seconds*60;i++){if(predicate())return;await frame();}check(predicate(),`${label}: ${JSON.stringify(S())}`);}
 async function walk(p,{sprint=true,tolerance=.22,timeout=90,followFloor=false}={}){
  p=p.toArray?.()??p;report.actions.push({kind:'walk',target:p,frame:report.frames});let best=Infinity,stuck=0;
  for(let i=0;i<timeout*60;i++){
   if(game.state==='won'){stop();return;}
   const dx=p[0]-game.playerPosition.x,dz=p[2]-game.playerPosition.z,d=Math.hypot(dx,dz);
   if(d<tolerance&&(followFloor||Math.abs(p[1]-game.playerPosition.y)<.65)){stop();return;}
   if(d<best-.005){best=d;stuck=0;}else stuck++;
   check(stuck<260,`Blocked walking to ${p}; at ${game.playerPosition.toArray()}`);
   turn(dx,dz);if(sprint)game.input.keys.add('ShiftLeft');else game.input.keys.delete('ShiftLeft');
   const speed=d<.65?Math.max(.16,d/.65):1;worldMove(dx/Math.max(d,.001)*speed,dz/Math.max(d,.001)*speed);await frame();
  }throw Error(`Walk timed out ${p}`);
 }
 async function look(p){stop();p=V(...(p.toArray?.()??p));for(let i=0;i<300;i++){
  game.scene.updateMatrixWorld(true);if(p.clone().sub(game.camera.position).dot(game.camera.getWorldDirection(V()))<0){game.yaw+=.16;await frame();continue;}
  // A fixed screen tolerance becomes almost a metre on the final long shot.
  // Converge to a world-scale target before pressing the ordinary fire input.
  const q=p.clone().project(game.camera),tolerance=Math.min(.005,.035/Math.max(1,p.distanceTo(game.camera.position)));
  if(i>20&&Math.abs(q.x)<tolerance&&Math.abs(q.y)<tolerance)return;
  game.yaw-=THREE.MathUtils.clamp(q.x,-1,1)*.21;game.pitch=THREE.MathUtils.clamp(game.pitch+THREE.MathUtils.clamp(q.y,-1,1)*.19,-1.15,1.15);await frame();
 }throw Error('Cannot aim at '+p.toArray());}
 async function shoot(slot,p){check(!game.heldCube,'Set companion down before firing');p=[...(p.toArray?.()??p)];const panel=game.portalPanels.find(a=>(a.userData.portalFrame?.()?.center??a.userData.center).distanceTo(V(...p))<.08);if(panel&&Math.abs((panel.userData.portalFrame?.()?.normal??panel.userData.normal).y)<.1)p[1]-=.4;await look(p);check(game.firePortal(slot),'Portal input rejected');report.shots++;report.actions.push({kind:'shoot',slot,...S()});await until(()=>!game.portalShots.queue.length&&!game.portalShots.active.length,4,'Unresolved shot');check(game.portalShots.lastImpact?.valid,'Invalid portal impact '+JSON.stringify(game.portalShots.lastImpact));}
 async function use(id,{approach=true,side=null}={}){const t=level.terminals.find(t=>t.id===id);check(t,'Unknown console '+id);if(approach)await walk([t.position.x,t.position.y-1,t.position.z+(side??(game.playerPosition.z<t.position.z?-1:1))*1.5]);check(!game.heldCube,'Hands occupied at '+id);check(game.interact(),'Interaction rejected '+id+' at '+game.playerPosition.toArray());report.interactions++;report.actions.push({kind:'use',id,...S()});await wait(.28);}
 async function pickup(){for(let i=0;i<4&&!game.heldCube;i++){
  const p=game.cargo.position;if(game.playerPosition.clone().add(V(0,1.1,0)).distanceTo(p)>1.9)await walk([p.x,game.playerPosition.y,p.z+1.1]);
  if(game.interact()&&game.heldCube){report.interactions++;await wait(.35);return;}await wait(.35);
 }check(game.heldCube,'Could not pick up original companion '+JSON.stringify(S()));}
 async function dropAt(p,dir=[0,-1]){await walk([p[0]-dir[0]*3,p[1],p[2]-dir[1]*3],{sprint:false});await walk([p[0]-dir[0]*.85,p[1],p[2]-dir[1]*.85],{sprint:false});await look([p[0]+dir[0]*3,p[1]+1,p[2]+dir[1]*3]);await wait(.4);check(game.heldCube&&game.interact(),'Drop failed');report.interactions++;await wait(1);}
 async function enter(panel){const f=panel.frame();check(Math.abs(f.normal.y)<.1,'Use falling input for floor portals');await walk(f.center.clone().addScaledVector(f.normal,1.6).setY(f.center.y-2.4).toArray());const old=game.teleportCount;
  for(let i=0;i<240&&game.teleportCount===old;i++){worldMove(-f.normal.x,-f.normal.z);await frame();}stop();check(game.teleportCount>old,'Portal crossing failed');await wait(.2);}
 async function jump(){check(game.playerGrounded,'Jump requires grounded feet');game.input.jumpQueued=true;report.jumps++;await frame();}
 function mark(name){const s={name,...S()};report.milestones.push(s);onMilestone(s,game);}
 const P=(id,x,z=0,y=0)=>level.rooms.get(id).P(x,z,y),st=id=>level.machines.get(id).state;
 const infrastructure=[...level.edges];
 async function travel(to){
  const start=game.playerPosition.toArray(),end=to.toArray?.()??to;const points=[start,end,...infrastructure.flat()];
  for(const [a,b]of infrastructure)for(const [c,d]of infrastructure){if(a[1]!==b[1]||c[1]!==d[1]||a[1]!==c[1])continue;
   const ax=a[0]!==b[0],cx=c[0]!==d[0];if(ax===cx)continue;const h=ax?[a,b]:[c,d],v=ax?[c,d]:[a,b],p=[v[0][0],a[1],h[0][2]];
   if(p[0]>=Math.min(h[0][0],h[1][0])-.01&&p[0]<=Math.max(h[0][0],h[1][0])+.01&&p[2]>=Math.min(v[0][2],v[1][2])-.01&&p[2]<=Math.max(v[0][2],v[1][2])+.01)points.push(p);
  }
  for(const p of [start,end]){let best=null,dist=Infinity;for(const [a,b]of infrastructure){const q=new THREE.Line3(V(...a),V(...b)).closestPointToPoint(V(...p),true,V());if(q.distanceTo(V(...p))<dist){dist=q.distanceTo(V(...p));best=q.toArray();}}if(best)points.push(best);}
  const map=new Map(points.map(p=>[p.map(n=>Math.round(n*100)/100).join(','),p]));const nodes=[...map.values()],adj=nodes.map(()=>[]);const si=nodes.findIndex(p=>p.every((v,i)=>Math.abs(v-start[i])<.006)),ei=nodes.findIndex(p=>p.every((v,i)=>Math.abs(v-end[i])<.006));
  for(const [a,b]of infrastructure){const line=new THREE.Line3(V(...a),V(...b)),near=nodes.map((p,i)=>({p,i,t:line.closestPointToPointParameter(V(...p),true)})).filter(n=>line.at(n.t,V()).distanceTo(V(...n.p))<.05).sort((x,y)=>x.t-y.t);
   for(let i=1;i<near.length;i++){const u=near[i-1].i,v=near[i].i,dist=V(...nodes[u]).distanceTo(V(...nodes[v]));adj[u].push([v,dist]);adj[v].push([u,dist]);}}
  for(const id of [si,ei]){if(adj[id].length)continue;let candidates=nodes.map((p,j)=>({j,d:V(...p).distanceTo(V(...nodes[id]))})).filter(v=>v.j!==id&&adj[v.j].length).sort((a,b)=>a.d-b.d);check(candidates.length,'Missing route junction');const v=candidates[0];adj[id].push([v.j,v.d]);adj[v.j].push([id,v.d]);}
  const distance=nodes.map(()=>Infinity),prev=nodes.map(()=>-1),visited=new Set();distance[si]=0;
  while(!visited.has(ei)){let u=-1;for(let i=0;i<nodes.length;i++)if(!visited.has(i)&&(u<0||distance[i]<distance[u]))u=i;check(u>=0&&Number.isFinite(distance[u]),'Disconnected infrastructure');visited.add(u);for(const [v,w]of adj[u])if(distance[u]+w<distance[v]){distance[v]=distance[u]+w;prev[v]=u;}}
  const route=[];for(let u=ei;u!==si;u=prev[u])route.unshift(nodes[u]);for(const p of route)await walk(p);
 }
 async function arrive(id){await travel(level.rooms.get(id).door);await walk(P(id,0,0));mark('Entered '+id);}
 async function leave(id,via=[]){for(const p of via)await walk(p);await walk(level.rooms.get(id).door);}
 const routines={
  async freight(){await travel([0,0,54]);await pickup();await travel(level.rooms.get('freight').door);await walk(P('freight',12,13));await dropAt(P('freight',12,13));await walk(P('freight',13,7));await shoot(0,st('freight').intake.center);await walk(P('freight',12,-10));await shoot(1,st('freight').outlet.center);await walk(P('freight',12,13));await pickup();await enter(st('freight').intake);await walk(st('freight').receiver);await until(()=>level.getTowerMetrics().solvedIds.includes('freight'),2,'Freight joint delivery');await enter(st('freight').outlet);await leave('freight',[P('freight',13,0)]);await travel([0,0,54]);await dropAt([2,0,54]);},
  async sluice(){await arrive('sluice');const capacities=st('sluice').capacities,queue=[{v:[10,0,0],route:[]}],seen=new Set(['10,0,0']);let route;
   for(let n=0;n<queue.length&&!route;n++){const node=queue[n];if(node.v.join(',')==='5,5,0'){route=node.route;break;}for(let a=0;a<3;a++)for(let b=0;b<3;b++)if(a!==b){const v=[...node.v],amount=Math.min(v[a],capacities[b]-v[b]);v[a]-=amount;v[b]+=amount;const key=v.join(',');if(!seen.has(key)){seen.add(key);queue.push({v,route:[...node.route,[a,b]]});}}}
   check(route,'Hydraulic target unreachable');for(const[a,b]of route){await use(`sluice:${a}-${b}`);await until(()=>!st('sluice').flowing,3,'Unfinished physical pour');}await walk(P('sluice',0,12));await until(()=>st('sluice').height>-.02,3,'Hydraulic span did not rise');await walk(P('sluice',0,22));await until(()=>level.getTowerMetrics().solvedIds.includes('sluice'),2,'Hydraulic receiving bank');await walk(P('sluice',0,12));await leave('sluice',[P('sluice',-18,12),P('sluice',-18,0)]);},
  async optics(){await travel(level.rooms.get('optics').door);await walk(P('optics',20,12));await walk(P('optics',-17,12));await use('optics:mirror');await walk(P('optics',-16,-1));await shoot(0,st('optics').intake.center);await walk(P('optics',-14,12));await walk(P('optics',3,12));await shoot(1,st('optics').outlet.center);await until(()=>level.getTowerMetrics().solvedIds.includes('optics'),3,'No reflected portal beam');await leave('optics',[P('optics',20,12),P('optics',28,0)]);},
  async hoist(){await travel([0,0,54]);await pickup();await travel(level.rooms.get('hoist').door);await walk(P('hoist',-18,-11));await dropAt(st('hoist').pad,[1,0]);await walk(P('hoist',0,-7));await walk(P('hoist',0,0));await use('hoist:lift');await until(()=>game.playerPosition.y>17.7,8,'Counterweight hoist did not rise');await walk(P('hoist',0,10,18));await use('hoist:pawl');await walk(P('hoist',-12,9,18));await shoot(1,st('hoist').outlet.center);await walk(P('hoist',-12,6.45,18));await shoot(0,st('hoist').intake.center);await until(()=>level.getTowerMetrics().solvedIds.includes('hoist'),7,'Original cargo did not reach upper catcher');await pickup();await walk(P('hoist',-18,10,18));await walk(P('hoist',-18,0,18));await walk([level.rooms.get('hoist').door[0],18,level.rooms.get('hoist').door[2]]);await travel([0,18,54]);await dropAt([2,18,54]);},
  async archive(){await travel(level.rooms.get('archive').door);await use('archive:slide-a');await walk(P('archive',12,-7));await walk(P('archive',-5,-7));await walk(P('archive',-5,-13));await walk(P('archive',-7,-13));await use('archive:slide-b');await walk(P('archive',-5,-13));await walk(P('archive',-5,7));await walk(P('archive',-15,7));await until(()=>level.getTowerMetrics().solvedIds.includes('archive'),2,'Rewired archive route');await walk(P('archive',-5,7));await walk(P('archive',-5,-13));await walk(P('archive',-5,-7));await walk(P('archive',12,-7));await leave('archive',[P('archive',14,0)]);},
  async flywheel(){await arrive('flywheel');await use('flywheel:ratio');await use('flywheel:crank');for(let i=0;i<4;i++)await use('flywheel:crank',{approach:false});await use('flywheel:clutch');if(st('flywheel').output>6){await use('flywheel:brake');await until(()=>st('flywheel').output<5.7,5,'Brake feedback');await use('flywheel:brake',{approach:false});}await until(()=>level.getTowerMetrics().solvedIds.includes('flywheel'),6,'Unstable output shaft');await leave('flywheel',[P('flywheel',13,0)]);},
  async magnet(){await travel([0,18,54]);await pickup();await travel(level.rooms.get('magnet').door);await walk(P('magnet',-16,0));await dropAt(st('magnet').sender,[1,0]);await walk(P('magnet',-17,-14));await use('magnet:coil-0');await until(()=>game.cargo.position.y>22.2,6,'Magnetic body did not rise');await use('magnet:coil-1');await until(()=>st('magnet').passed&&Math.abs(game.cargo.position.x-P('magnet',0)[0])<.15&&game.cargo.position.z>P('magnet',0,10.9)[2],10,'Cargo did not settle in the physical loading slit');await walk(P('magnet',-19,-9.5));await walk(P('magnet',-19,6.5));await use('magnet:coil-2');await until(()=>Math.hypot(game.cargo.position.x-P('magnet',12)[0],game.cargo.position.z-P('magnet',0,0)[2])<.5,12,'Cargo missed catcher');await use('magnet:coil-2',{approach:false});await until(()=>level.getTowerMetrics().solvedIds.includes('magnet'),6,'Cargo did not settle on real receiver');await until(()=>st('magnet').serviceProgress>.99,3,'Magnetic receiver did not release service door');await walk(P('magnet',-19,6.5));await walk(P('magnet',-19,-14));await walk(P('magnet',20.2,-14));await walk(P('magnet',20.2,18.8));await walk(P('magnet',18,18.8));await walk(P('magnet',18,3,4.2));await walk(P('magnet',13,2,4.2));await pickup();await walk(P('magnet',18,3,4.2));await walk(P('magnet',18,18.8));await walk(P('magnet',20.2,18.8));await walk(P('magnet',20.2,-14));await walk(P('magnet',-17,-14));await leave('magnet',[P('magnet',-17,0)]);await travel([0,36,54]);await dropAt([2,36,54]);},
  async migrant(){await travel(level.rooms.get('migrant').door);await walk(P('migrant',-12,12));await shoot(0,st('migrant').intake.center);await walk(P('migrant',-13,0));await shoot(1,st('migrant').moving.frame().center);await use('migrant:rail');await walk(P('migrant',-12,12));await until(()=>st('migrant').travel>.99,7,'Carriage did not reach opposite bank');await leave('migrant',[P('migrant',-12,0)]);await travel([0,36,54]);await pickup();await travel(level.rooms.get('migrant').door);await enter(st('migrant').intake);await walk(P('migrant',12,10,3));await until(()=>level.getTowerMetrics().solvedIds.includes('migrant'),2,'Joint carriage delivery');await enter(st('migrant').moving);await leave('migrant',[P('migrant',-12,12),P('migrant',-12,0)]);await travel([0,36,54]);await dropAt([2,36,54]);},
  async pendulum(){await travel(level.rooms.get('pendulum').door);await walk(P('pendulum',24,-19));await walk(P('pendulum',-17,-19));await walk(P('pendulum',-17,-12));await until(()=>st('pendulum').ya<.15,11,'First span catch window');await use('pendulum:catch-a');await walk(P('pendulum',-19,-10));await walk(P('pendulum',-19,0));await jump();worldMove(1,0);for(let i=0;i<50;i++)await frame();stop();await walk(P('pendulum',-8,0));await walk(P('pendulum',0,0));await until(()=>st('pendulum').yb<.2,11,'Second span boarding window');await walk(P('pendulum',7,0),{followFloor:true});await until(()=>st('pendulum').yb>5.9,11,'Second span did not lift');await walk(P('pendulum',12,-1.3,6),{followFloor:true});await until(()=>st('pendulum').yb>5.99,11,'Raised span jump window');await wait(.15);game.input.keys.add('ShiftLeft');worldMove(0,1);for(let i=0;i<32;i++)await frame();await jump();worldMove(0,1);for(let i=0;i<70;i++)await frame();stop();await until(()=>game.playerGrounded&&game.playerPosition.y>41.8,2,'Upper return landing');await walk(P('pendulum',15,9.5,6));await until(()=>st('pendulum').yb>5.78,11,'Second catch window');await use('pendulum:catch-b');await until(()=>level.getTowerMetrics().solvedIds.includes('pendulum'),2,'Two catches not engaged');await walk(P('pendulum',19,11,6));await walk(P('pendulum',19,-13));await until(()=>st('pendulum').stairProgress>.99,3,'Upper catch did not open return stair');await walk(P('pendulum',19,-19));await leave('pendulum',[P('pendulum',24,-19),P('pendulum',24,0)]);},
  async inertia(){await travel(level.rooms.get('inertia').door);await walk(P('inertia',30,12));await walk(P('inertia',30,16));await walk(P('inertia',-22,16));await walk(P('inertia',-22,12));await walk(P('inertia',-22,-4));await shoot(0,st('inertia').intake.center);await walk(P('inertia',-22,12));await walk(P('inertia',-10,12));await shoot(1,st('inertia').outlet.center);await walk(P('inertia',-27,10));await walk(P('inertia',-27,-14,12));await walk(P('inertia',-1,-14,12));await walk(P('inertia',-1,-11.35,12),{sprint:false,tolerance:.06});const before=game.teleportCount;
   for(let i=0;i<8*60&&game.teleportCount===before;i++){if(game.playerGrounded)worldMove(0,.42);else{const entry=game.portals.portals[0].position,p=game.playerPosition,v=game.playerVelocity,steer=V((4*(entry.x-p.x)-3*v.x)/2.8,0,(4*(entry.z-p.z)-3*v.z)/2.8);if(steer.length()>1)steer.normalize();worldMove(steer.x,steer.z);}await frame();}stop();check(game.teleportCount>before,'Real falling aperture missed');await until(()=>game.playerGrounded,6,'Momentum crossing did not land');await walk(P('inertia',21,0,-3.5));await until(()=>level.getTowerMetrics().solvedIds.includes('inertia'),2,'Receiver balcony not reached');await walk(P('inertia',22,3,-3.5));await until(()=>st('inertia').returnProgress>.99,3,'Receiver did not release the return door');await walk(P('inertia',22,13));await leave('inertia',[P('inertia',30,13),P('inertia',30,0)]);},
  async crown(){await travel([0,36,54]);await pickup();await travel([0,72,54]);await travel(level.rooms.get('crown').door);await walk(P('crown',12,13));await dropAt(P('crown',12,13));await walk(P('crown',13,7));await shoot(0,st('crown').intake.center);await walk(P('crown',12,-10));await shoot(1,st('crown').outlet.center);await walk(P('crown',12,13));await pickup();await enter(st('crown').intake);await dropAt(st('crown').socket);await walk(st('crown').contact);await until(()=>game.state==='won',3,'Independent crown loads not closed');},
 };
 try{const sequence=order??['freight','sluice','optics','hoist','archive','flywheel','magnet','migrant','pendulum','inertia','crown'];for(const id of sequence){check(routines[id],'Unknown route '+id);mark('Start '+id);await routines[id]();check(level.getTowerMetrics().solvedIds.includes(id),'Missing solved mechanism '+id);mark('Solved '+id);await globalThis.__SINGULARITY_FLUSH__?.();if(stopAfter===id){report.partial=true;break;}}
  report.pass=!report.partial&&game.state==='won';report.seconds=report.physicsSteps/120;report.teleports=game.teleportCount;report.metrics=level.getTowerMetrics();report.sameCompanion=game.cargo===companion&&game.physics.cargoBody.id===body;return report;
 }catch(error){report.seconds=report.physicsSteps/120;report.failure={error:String(error),...S()};report.metrics=level.getTowerMetrics();error.singularityReport=report;throw error;}
 finally{stop();game.input.getMove=original.move;game.resetRun=original.reset;game.respawn=original.respawn;game.physics.resetCargo=original.cargoReset;await globalThis.__SINGULARITY_FLUSH__?.();}
}
