import test from 'node:test';import assert from 'node:assert/strict';import {SiphonCircuit} from '../src/game/LabSiphonCircuit.js';
const advance=(c,seconds,load=0,dt=1/120)=>{for(let i=0;i<seconds/dt;i++){c.step(dt,typeof load==='function'?load(i*dt):load);assert.ok(Math.abs(c.volume-c.total)<1e-9);assert.ok(c.source>=0&&c.ram>=0&&c.tube>=0);}};
test('an empty cistern, elapsed time and pump alone cannot prime the dry crest',()=>{const c=new SiphonCircuit();advance(c,60);assert.equal(c.height,0);c.returning=true;advance(c,20);c.returning=false;advance(c,30);assert.equal(c.tube,0);assert.equal(c.height,0);});
test('real displaced volume primes, subsequent below-crest flow retains one conserved volume',()=>{const c=new SiphonCircuit();advance(c,1,.78**3);assert.ok(c.primed);advance(c,40,0);assert.equal(c.height,c.maxHeight);assert.ok(c.surface<c.crest);assert.ok(c.primed);});
test('insufficient immersion cannot create flow; separate partial wettings drain instead of becoming achievements',()=>{const c=new SiphonCircuit();advance(c,20,.10);assert.equal(c.tube,0);for(let n=0;n<20;n++){advance(c,.1,.28);advance(c,3,0);}assert.equal(c.height,0);assert.equal(c.tube,0);});
test('actual crest airing stops circulation and drains its liquid back to the source',()=>{const c=new SiphonCircuit({ramArea:.4,maxHeight:12});advance(c,60,.48);advance(c,10,0);assert.ok(c.surface<c.intake+.013);assert.ok(c.tube<c.tubeCapacity);const before=c.ram;advance(c,10,0);assert.equal(c.ram,before);});
test('service motor lowers the ram without spawning water and must be turned off to prime again',()=>{const c=new SiphonCircuit();advance(c,30,.48);assert.ok(c.height>10);c.returning=true;advance(c,30,.48);assert.equal(c.height,0);assert.equal(c.tube,0);assert.ok(Math.abs(c.source-c.total)<1e-9);c.returning=false;advance(c,30,.48);assert.equal(c.height,c.maxHeight);});
test('small physics timesteps converge without changing the rule',()=>{const heights=[1/30,1/60,1/120,1/240].map(dt=>{const c=new SiphonCircuit();advance(c,8,.48,dt);return c.height;});assert.ok(Math.max(...heights)-Math.min(...heights)<.05);});
test('reset restores liquid volumes, air and service valve; invalid inputs are rejected',()=>{const c=new SiphonCircuit();advance(c,20,.48);c.returning=true;c.reset();assert.equal(c.primed,false);assert.equal(c.returning,false);assert.equal(c.ram,0);assert.equal(c.source,c.total);for(const dt of [-1,NaN,Infinity,.2])assert.throws(()=>c.step(dt));assert.throws(()=>c.step(.01,-1));});
