import test,{after} from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import fs from 'node:fs';
import {createHeadlessGame} from '../scripts/lab-headless.mjs';import {runV8Journey} from '../src/game/LabV8Journey.js';import {runSiphonObservatory} from '../src/game/LabSiphonObservatoryJourney.js';import {installPreciseLateAim,aimLateSurface} from '../src/game/LabLateCampaignAim.js';import {LabPreferences,CREATIVE_CAMPAIGN_REVISION} from '../src/game/LabPreferences.js';
const g=await createHeadlessGame();g.chamberEdition='foundation';after(()=>{g.firstLevel.dispose?.();g.physics.dispose();g.portals.dispose();});
for(const options of [{},{swapColours:true},{route:'miss-lift-and-recirculate'}])test('33 ordinary-input siphon route '+JSON.stringify(options),async()=>{await g.selectLevel(32,false);const cargo=g.cargo,body=g.physics.cargoBody,events=[];const r=await runV8Journey(g,{journeyOptions:options,onMilestone:m=>{events.push({name:m.name,volume:g.firstLevel.circuit.volume,primed:g.firstLevel.circuit.primed});assert.ok(Math.abs(g.firstLevel.circuit.volume-g.firstLevel.circuit.total)<1e-9);}});assert.equal(r.pass,true);assert.equal(g.state,'won');assert.equal(r.resets+r.respawns,0);assert.equal(g.cargo,cargo);assert.equal(g.physics.cargoBody,body);assert.equal(g.firstLevel.id,'siphon-observatory');assert.equal(g.firstLevel.spring,undefined);assert.ok(g.physics.portalTransports>0);assert.ok(r.teleports>0);if(options.route)assert.ok(r.milestones.some(m=>m.name.includes('missed lift recovered')));g.resetRun(true);assert.equal(g.firstLevel.circuit.height,0);assert.equal(g.firstLevel.circuit.primed,false);assert.equal(g.firstLevel.basket.height,12);});
test('dry header is not a timer and a nearby non-submerged load cannot move the ram',async()=>{await g.selectLevel(32,false);await runV8Journey(g,{scenario:d=>{d.walk(11,16.8);d.pickup();d.walk(1,7);d.wait(40);assert.equal(d.level.circuit.height,0);assert.equal(d.level.getDisplacement(),0);assert.equal(d.level.circuit.primed,false);}});});
for(const x of [-7,0,27])test('actual lower bulkhead jump and sprint attack at x='+x,async()=>{await g.selectLevel(32,false);await runV8Journey(g,{scenario:d=>{d.walk(x,26);d.walk(x,-5);assert.ok(Math.abs(g.playerPosition.z+5)<.3);let max=0,min=100;for(let i=0;i<360;i++){g.input.keys.add('ShiftLeft');if(i%45===0)g.input.jumpQueued=true;d.worldMove(0,-1);d.frame();max=Math.max(max,g.playerPosition.y);min=Math.min(min,g.playerPosition.z);}assert.ok(max>1);assert.ok(min>-7.6);assert.equal(d.level.circuit.height,0);assert.equal(g.state,'playing');}});});
test('deleting the cargo pair after priming cannot empty a physical tube or lower the checked ram',async()=>{await g.selectLevel(32,false);await runV8Journey(g,{scenario:async d=>{await runSiphonObservatory(d,{stopAfter:'primed'});const before=d.level.circuit.ram;assert.ok(g.clearPortals());d.wait(10);assert.equal(g.portals.ready,false);assert.ok(d.level.circuit.ram>before+.5);assert.ok(d.level.circuit.primed);assert.ok(d.level.circuit.surface<d.level.circuit.crest);}});});
test('only old33 completion is invalidated; completed Echo Horizon and player preferences survive',()=>{const key='brainrot-portal.preferences.v24',db=new Map([[key,JSON.stringify({campaignRevision:CREATIVE_CAMPAIGN_REVISION,completed:[0,8,32,50],hints:{8:1,32:2,50:1},roomRevisions:{50:'echo-horizon-v1'},volume:.2,quality:'high',resumeLevel:32})]]);const storage={getItem:k=>db.get(k),setItem:(k,v)=>db.set(k,v)},options={campaignRevision:CREATIVE_CAMPAIGN_REVISION,roomRevisions:{32:'siphon-observatory-v1',50:'echo-horizon-v1'}};let p=new LabPreferences(storage,options);assert.deepEqual(p.value.completed,[0,8,50]);assert.deepEqual(p.value.hints,{8:1,50:1});assert.equal(p.value.volume,.2);assert.equal(p.value.resumeLevel,32);p.complete(32);p=new LabPreferences(storage,options);assert.ok(p.value.completed.includes(32)&&p.value.completed.includes(50));});
test('old inverse-spring builder and route are removed, not hidden behind a renamed spec',()=>{for(const file of ['LabLateCampaignSpringRoom.js','LabLateCampaignSpringJourney.js'])assert.equal(fs.existsSync(new URL('../src/game/'+file,import.meta.url)),false);});
